### ISSUE TITLE
"The template output 'vnet_name' is not valid: The language expression property 'vnetName' doesn't exist"

### ISSUE THREAD

**Issue by OceaneLonneux-CAL** [cpu601/terraform-azurerm-hcs#5]
Hello, I am using your template to deploy automatically with Terraform a Consul Cluster.
I am facing an issue where I am getting: 

`
'" Details=[{"code":"DeploymentOutputEvaluationFailed","message":
"The template output 'vnet_name' is not valid: The language expression property 'vnetName' doesn't exist, 
available properties are 'state, storageAccountName, blobContainerName, storageAccountResourceGroup, location, consulInitialVersion, consulCurrentVersion, 
consulDatacenter, consulNumServers, consulAutomaticUpgrades, consulExternalEndpoint, consulSnapshotInterval, consulSnapshotRetention, managedAppId, consulConfigFile, 
consulCaFile, consulConnect, consulVnetCidr, consulPrivateEndpointUrl, consulClusterId, email'..","target":"vnet_name"}]
`

Here is my main.tf : 
```
module "hcs" {
  source  = "cpu601/hcs/azurerm"
  version = "0.6.0"
  application_name             = "hcs"
  consul_cluster_name          = "consul-something"
  email                        = "something@something.com"
  resource_group_name          = module.res_group.name
  consul_cluster_mode          = "PRODUCTION"
  region                       = "uksouth"
  accept_marketplace_aggrement = "true"
}
```
(we set up the resource name in another module)

outputs.tf:
```
output "consul_url" {
  value = module.hcs.consul_url
}
```

Thank you for your help!

**Comment by cpu601** [comment]
Hi @OceaneLonneux-CAL ,

thanks for highlighting this.

Some default variables are outdated within the module and also the HCS internal vnet naming convention changed, so simply setting those outdated variables manually to the current values will not work properly.

Will provide an updated version of the module during the next days.

**Comment by OceaneLonneux-CAL** [comment]
Hello, thank you for answering!

Is there any chance you could give me an estimated ETA? (Just so I know how to organise my work)

**Comment by cpu601** [comment]
Hey, I don't want to make any promises, but we are trying to ship it by the end of the week...

**Comment by OceaneLonneux-CAL** [comment]
No pressure, thanks a lot for your help

**Comment by cpu601** [comment]
Hey @OceaneLonneux-CAL,

thanks to the help of @timarenz we just shipped a new version of the module which hopefully avoids these kind of errors looking forward, as it automatically checks for the latest API version.

Hence, closing this issue for now.
